### PR TITLE
Rent-burdened map

### LINKED ISSUE #49: Add rent burdened map
Thing’s we’ll need:
1. 16:9 screenshot of map (probably without any text in the screenshot—no definition, etc) for thumbnail.
2. Title of map for website homepage (and menu).
3. Short description of map (similar to what’s there for the tenant stories map).
4. Embed code for the map.

Creating an issue for this. It will probably involve a little bit of a refactor of the _layouts/map.html file. I have something in mind already.

Psst... @pizzavangelist @beccalou @aliceriot

### PR DESCRIPTION
**Pull request by heybenji**
Closes #49 when merged.

### CODE REVIEW

**Comment by heybenji** [comment]
@aliceriot and @beccalou could you pull this branch down and check it out? I think everything is set.

**Comment by alicewriteswrongs** [comment]
it looks great on the desktop!

I haven't tried it on a real device, but in the Chrome mobile simulator it's a bit strange, I can't seem to move the map around. this could be some sort of native device gesture thingy that the browser doesn't support.

the map also scrolls vertically just a tiny amount on mobile in Chrome (again, not sure about a real device).

**Comment by heybenji** [comment]
Cool seems like some more testing is in order before merging. Works great on Safari Desktop and iOS simulator.

@aliceriot can you try the other map on Android simulator and let me know if that also scrolls a tiny bit? Using calc() and I'm wondering if it's supported on that version?

The map is in an iframe so we have no control over behavior or code.

**Comment by alicewriteswrongs** [comment]
ahhh gotcha

I can install android studio (should anyway really) and check! although it might take a while b/c I'm busy in a bit.

**Comment by beccalou** [comment]
Desktop looks very good in Chrome and Safari my end-- maps move, clicking areas on the map launches the little window with more information.   Do we know the year the data from this map was collected?

**Comment by heybenji** [comment]
Yes I believe it's 2011-14 ACS data.

Probably should be somewhere as a legend or in the desc.

**Comment by heybenji** [comment]
I'm merging this. No reason to delay this. I've created another bug issue (#54) to deal with the fact that the rent-burdened map might not be fully-functional on Android.

**Comment by heybenji** [comment]
This also closes https://github.com/AntiEvictionBoston/Maps/issues/80

**Pull request merged**
