### PR TITLE
Email script

### PR DESCRIPTION
**Pull request by beccalou**
Added Contributors URL to footer.  Resolved conflicts in css/main.scss (accepted current file, didn't overwrite anything)

### CODE REVIEW

**Comment by heybenji** [comment]
@beccalou this looks great I'll merge momentarily.

**Comment by heybenji** [comment]
So this is merged @beccalou one thing I didn't notice at first was that you hard-linked the full website URL, which is generally not a great idea if we ever decide to change URLs or move the site into a subdirectory.

The Jekyll-y way to do it would be:

`<a href="{{ '/contributors/' | prepend: site.baseurl }}">Contributors</a>`

Which basically is a root-relative link, prepended with the `site.baseurl` in `_config.yml` (which is currently nothing). The result would be:

`<a href="/contributors/">Contributors</a>` 

and if we ever moved it into a directory (say `/archive` then we could set the `site.baseurl` to that and the output would be:

`<a href="/archive/contributors/">Contributors</a>`

Possibly TMI. Sorry.

**Comment by heybenji** [comment]
So I was doing some accessibility work that touched those files and I fixed it as a matter of course.

Before you do much else I would checkout master and do a pull and work off a new branch off of master. A fair amount has changed.

I actually removed the bower bootstrap in favor of vanilla bootstrap hosted off their CDN because it's faster and we're not really doing any of the advanced sass stuff and I needed to add the JS too and it would have been harder to figure out bower than link to the CDN files.

**Comment by beccalou** [comment]
As you wish : )

**Comment by heybenji** [comment]
Sorry :-D

## 

Benji Mauer
617-283-5764
@heybenji
www.heybenji.co

**Pull request merged**
